### ISSUE TITLE
Defib clearing the HealingSourceStack causes NREs and potential crash

### ISSUE THREAD

**Issue by svrakiss** [ThinkInvis/RoR2-TinkersSatchel#54] opened 2022-05-02 22:38 UTC
### Describe the Bug
Attacking enemies while you have items that heal on hit or damage creates a stutter that eventually crashes the game.

This happens even if Defib is not in the inventory. When you heal too quickly, the game stutters as the title suggests. The error appears to happen every time you heal from a hit. 

### To Reproduce
1. Equip an item like leeching seed/defibrillator
2. Attack and score a hit/crit on an enemy
3. Inspect log

### Expected Behavior
I expect to receive healing and not have the game freeze. 

### Console Log
**Please include a link or embed of a FULL console log file from a run of the game where the bug happened**. This will provide a versioned mod list, and possibly other important information about the bug.

This one crashed the game, but several hours into the run. I attacked a group of enemies.
[LogOutput.log](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/8606099/LogOutput.log)

Recent:
Loaded game, attacked 1 enemy then summoned and killed 2 mini bosses with rockets. 
[LogOutput.log](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/8606253/LogOutput.log)

Most recent:
Loaded game and attacked once (3 bullets).
[LogOutput.log](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/8606286/LogOutput.log)

**Comment by ThinkInvis** [comment] 2022-05-03 00:11
This appears to be a bug with the new Old-War Lidar VFX; likely an incompatibility with another mod, as I was unable to reproduce this during testing (but nothing some extra null safety won't fix). The error with Defibrillator is a chain reaction.

**Comment by ThinkInvis** [comment] 2022-05-03 02:33
Probable fix published in v2.3.3 (936a27fc584bfa1063fae3672f1d5e1d58c93e43, 11cc5a374afe681e1c91fc289adde95b3399f594). Please reopen and post a new log if the bug reoccurs (signature changed and may provide a different, more useful error).

**Closed by ThinkInvis** 2022-05-03 02:33 UTC
Labels: bug
