### ISSUE TITLE
Artifacts show in Eclipse mode

### ISSUE THREAD

**Issue by PollyEdaline** [ThinkInvis/RoR2-TinkersSatchel#32] opened 2022-04-02 17:10 UTC
### Describe the Bug
The Artifacts added by the mod are selectable in Eclipse.

### To Reproduce
1. Select any Survivor and enter the Eclipse start screen.
2. Artifacts can now be selected that affect the run.

### Expected Behavior
Artifacts should not be selectable in Eclipse (at least not without an external mod).

**Comment by ThinkInvis** [comment] 2022-04-02 18:31
Duplicate of https://github.com/ThinkInvis/RoR2-TILER2/issues/27.

**Closed by ThinkInvis** 2022-04-02 18:31 UTC
Labels: duplicate
