### ISSUE TITLE
Mimic blacklist scrap please.

### ISSUE THREAD

**Issue by kurosnow** [ThinkInvis/RoR2-TinkersSatchel#3] opened 2020-08-28 14:38 UTC
Had two white scrap, two mimics, the mimics were copying the scrap, and hit a printer, the printer ate a bunch of items and printed out an item I couldn't take. 

https://pastebin.com/A5n75FcW

**Comment by ThinkInvis** [comment] 2020-08-28 21:51
Can't reproduce, and that error doesn't seem to be directly related to the given situation. This could possibly be another mod changing the ItemCatalog after it's been set up (which really shouldn't be done), or a mismatch in registered items between client and server (if this happened in multiplayer). A full console log would be more helpful.

**Comment by ThinkInvis** [comment] 2020-08-28 21:58
This symptom will be fixed in the next TILER2 update (https://github.com/ThinkInvis/RoR2-TILER2/commit/df775c16625fb30ea1b3c33318e3398d1b6d83d5), but it's probably not the cause.

**Comment by kurosnow** [comment] 2020-08-29 00:17
There was nothing else big in the log so it was a lot of spam with mostly NREs about enemies, but here it is if you want. https://pastebin.com/bLdC2T8J

The bug happened in single player.

**Comment by ThinkInvis** [comment] 2020-08-29 00:56
Confirmed as a conflict between TILER2.FakeInventory and OrderedItems, and I think I see what's going wrong in the OrderedItems code. Either way, it's not an issue with TinkersSatchel specifically (Admiral can trigger it as well). Closing and referring to https://github.com/gog909/Ordered-Items/issues/2 for the time being.

**Closed by ThinkInvis** 2020-08-29 00:56 UTC
Labels: unconfirmed-bug
